### ISSUE TITLE
Comparison to stow

### ISSUE THREAD

**Issue by mo8it** [TheRealLorenz/dotlink#1]
Could you please add a comparison to stow. I would love to have a stow alternative in Rust.

**Comment by TheRealLorenz** [comment]
I'll add a comparison with other software when I have some spare time. In the meanwhile I can tell you the main differences with stow.

First thing is, you need a configuration file in order to make it work. It's really simple to write, but it allows you pick which files to link, where to link it (eventually changing its name) and also to define different presets.

This features give the ability to store your dotfiles in any folder you'd like (I know there's an option in stow, but most people just clone to ~/.dotfiles), without being restricted to a child folder of your destination. 

They ability to rename files also gives the ability to mantain a different structure in the dotfiles repo than in your actual system.
For instance, a stow dotfiles repo should organized like:
```
.config/
    alacritty/
    lf/
    stuff/
.zshrc
 ```

With dotlink your dotfiles repo could become:
```
alacritty/
lf/
stuff/
rc.zsh
dotlink.toml
```

Then in the `dotlink.toml` you need to specify all linkings, in this case:
```toml
[[default]]
names = [ 'alacritty', 'lf', 'stuff' ]
to = '~/.config'

[[default]]
name = 'rc.zsh'
to = '~/.zshrc'
```

Hope this helps!

**Comment by mo8it** [comment]
Thank you for the detailed reply ^^

**Comment by mo8it** [comment]
Tried to boost it on Mastodon: https://fosstodon.org/@mo8it/110222512512240619

Just waiting for the publishing on crates.io to try it out ^^

**Comment by TheRealLorenz** [comment]
> Tried to boost it on Mastodon: https://fosstodon.org/@mo8it/110222512512240619
> 
> Just waiting for the publishing on crates.io to try it out ^^

Now online on: https://crates.io/crates/dotlink :)
